language: java

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database cars_sale;' -U postgres

sudo: false

env:
  global:
    - CODECOV_TOKEN="fa13fb95-3aa8-4350-9da8-2541382f19cb"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -s_manannikov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always